M48
; DRILL file {KiCad 9.0.0} date 2026-02-17T21:29:18-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-17T21:29:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.575
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.251
%
G90
G05
T1
X150.26Y-99.77
X150.26Y-115.37
T2
X130.0Y-120.0
X147.5Y-80.0
X147.5Y-120.0
T3
X146.75Y-101.855
X146.75Y-113.285
M30
